# Generated by Django 4.2.11 on 2024-08-22 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_remove_section_parent_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.section'),
        ),
        migrations.AddField(
            model_name='answer',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question.subsection'),
        ),
    ]
