# Generated by Django 4.2.11 on 2024-08-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_answer_section_answer_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_answers', to='question.subsection'),
        ),
        migrations.CreateModel(
            name='Subsubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubsections', to='question.subsection')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='subsubsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsub_answers', to='question.subsubsection'),
        ),
        migrations.AddField(
            model_name='question',
            name='subsubsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubsection_questions', to='question.subsubsection'),
        ),
    ]
