# Generated by Django 4.2.11 on 2024-08-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_alter_answer_subsection_subsubsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubsection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='question.section'),
        ),
    ]
