# Generated by Django 4.2.11 on 2024-08-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_subsubsection_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubsection',
            name='section',
        ),
    ]
